### ISSUE TITLE
Editing Method

### ISSUE THREAD

**Issue by daoyuan98** [betterze/TurboEdit#3]
Thank you for your great work.

For the editing method, did you use something like Prompt-to-Prompt (except for the first step where you freeze the attention maps)?  Or did you just change the source prompt to target prompt and generate images on the inverted noise, without other operations?

**Comment by betterze** [comment]
Please refer to section 3.4 in the paper. We use long detailed source and target prompts directly, without attention control.

**Comment by daoyuan98** [comment]
Thanks for the reply. For the results in Table 1, did you use long detailed prompts or just the short source and target prompts in PIE-Bench?

**Comment by betterze** [comment]
In Table 1, we use the short text prompt from the PIE bench, with attention control in the first step. 

We also have a version with an instruction prompt in Sup Table 3. We use the instruction prompt from PIE bench, and source target prompt from LLAVA. And we do not use attention freezing.

**Comment by daoyuan98** [comment]
Noted. Thanks again for the reply!
